# Generated by Django 2.2.19 on 2021-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_by', models.CharField(max_length=30)),
                ('transferred_to', models.CharField(max_length=30)),
                ('amount2', models.IntegerField(null=True)),
            ],
        ),
    ]
